#version: '3.8'
#services:
#  mysql:
#    image: mysql:latest
#    container_name: mysql_db
#    environment:
#      MYSQL_ROOT_PASSWORD:
#      MYSQL_DATABASE:
#      MYSQL_USER:
#      MYSQL_PASSWORD:
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#  app:
#    env_file:
#      - .env
#volumes:
#  mysql_data:
