spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: redis-15365.crce219.us-east-1-4.ec2.redns.redis-cloud.com
      port: 15365
      username: default
      password: GqnnpkZYKkGNA2l59bwpqK1MJlgSqRzh

  mail:
    host: smtp.gmail.com
    port: 587
    username: duongsatwintoplegends@gmail.com
    password: krywsccybyojfugl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  valid-duration: 3600
  refreshable-duration: 2592000

cloudinary:
  cloud-name:
  api-key:
  api-secret:
